version: "3.7"

#
# All-in-one docker-compose file to develop this Flarum extension.
#
# Initialization:
#   docker exec -it -w /flarum/app flarum-dev /bin/sh
#   composer config repositories.0 path "packages/*"
#   composer require jeromegillard/flarum-osm *@dev
#

services:
  flarum-dev:
    image: mondedie/flarum:stable
    container_name: flarum-dev
    env_file:
      - .env
      - flarum-dev.env.local
    restart: unless-stopped
    depends_on:
      - flarum-dev-db
    volumes:
      - ${FL_DIR}:/flarum/app/packages/osm
    ports:
      - 80:8888
    networks:
      - flarum-dev

  flarum-dev-db:
    image: mariadb:10.5.9
    container_name: flarum-dev-db
    env_file:
      - .env
      - flarum-dev.env.local
    restart: unless-stopped  
    networks:
      - flarum-dev

networks:
  flarum-dev: